name: Build Dev

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    name: Build and deploy dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Build
        run: yarn build

      - uses: jakejarvis/s3-sync-action@master
        name: Deploy to dev
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.S3_REGION }}
          SOURCE_DIR: 'build'
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
