name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn --no-progress --non-interactive --no-lockfile

      - name: Run tests
        run: yarn test
